Lesson7

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/usr/local/python/3.14.2/lib/python3.14/site-packages/numpy/__init__.py'>

Create Array

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1,2,3,5,7,12])

In [8]:
a

array([ 1,  2,  3,  5,  7, 12])

In [9]:
a[2] = 10

In [10]:
a

array([ 1,  2, 10,  5,  7, 12])

In [14]:
np.arange(1,-3,-1)

array([ 1,  0, -1, -2])

In [17]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [18]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])

In [24]:
n[0,1] = 20

In [25]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [26]:
n[0]

array([ 1, 20,  3])

In [30]:
n[:,2] = [0,1,2]

In [31]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 7,  8,  2]])

Randomly generated arrays

In [35]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [36]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [39]:
np.random.seed(2)
np.random.randint(low=10,high=100,size=(5,2))

array([[50, 25],
       [82, 32],
       [53, 92],
       [85, 17],
       [44, 59]])

Element-wise operations

In [40]:
a = np.arange(5)

In [41]:
a *2

array([0, 2, 4, 6, 8])

In [42]:
a/ 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [45]:
b = (10 + (a * 2) )**2 / 100

In [46]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [47]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

In [49]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

In [51]:
a >= 2

array([False, False,  True,  True,  True])

In [52]:
a > b

array([False, False,  True,  True,  True])

In [53]:
a[a>b]

array([2, 3, 4])

Summarizing operations

In [54]:
a.min()

np.int64(0)

In [55]:
a.sum()

np.int64(10)

In [56]:
a.mean()

np.float64(2.0)

In [57]:
a.std()

np.float64(1.4142135623730951)

In [61]:
n.min()

np.int64(0)

Lesson8: Linear Algebra

In [62]:
v = np.array([1,0,0,2])

In [63]:
u = np.array([2,4,5,6])

In [73]:
u.shape[0]

4

In [68]:
u * v

array([ 2,  0,  0, 12])

In [75]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result += u[i]*v[i]
    return result 

In [76]:
vector_vector_multiplication(u,v)

np.float64(14.0)

In [77]:
u.dot(v)

np.int64(14)

In [78]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [84]:
U[0].dot(v)

np.int64(14)

In [87]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = U[i].dot(v)

    return result

In [88]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [89]:
U.dot(v)

array([14,  5,  5])

In [90]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])

In [91]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

Identity Matrix

In [93]:
I = np.eye(3)

In [94]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [95]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

Inverse

In [106]:
Vs = V[[0,1,2]]

In [107]:
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [108]:
Vs_inv = np.linalg.inv(Vs)

In [109]:
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [110]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])